### ISSUE TITLE
Using HttpClient and configuration option singleton result in "Your Okta URL is missing"

### ISSUE THREAD

**Issue by pilouk** [okta/okta-auth-dotnet#53]
I'm doing a simple project .net5.0 with the configuration below:
```
public void ConfigureServices(IServiceCollection services)
{
    services.AddHttpClient<IOktaClient, OktaClient>();
    services.AddHttpClient<IAuthenticationClient, AuthenticationClient>();
    services.AddSingleton(new OktaClientConfiguration
    {
       OktaDomain = Configuration["Management:Okta:Domain"],
       Token = Configuration["Management:Okta:Token"]
    });
}
```
This works fine with the IOktaClient but doesn't work for the IAuthenticationClient which result with the following error : 
```
System.ArgumentNullException: Your Okta URL is missing. You can copy your domain from the Okta Developer Console. Follow these instructions to find it: https://bit.ly/finding-okta-domain (Parameter 'OktaDomain')
         at Okta.Sdk.Abstractions.OktaClientConfigurationValidator.Validate(OktaClientConfiguration configuration)
         at Okta.Sdk.Abstractions.BaseOktaClient..ctor(OktaClientConfiguration apiClientConfiguration, HttpClient httpClient, ILogger logger, UserAgentBuilder userAgentBuilder, AbstractResourceTypeResolverFactory resourceTypeResolverFactory)
         at Okta.Auth.Sdk.AuthenticationClient..ctor(OktaClientConfiguration apiClientConfiguration, HttpClient httpClient, ILogger logger)
         at lambda_method62(Closure , IServiceProvider , Object[] )
         at Microsoft.Extensions.Http.DefaultTypedHttpClientFactory`1.CreateClient(HttpClient httpClient)
         at Microsoft.Extensions.DependencyInjection.HttpClientBuilderExtensions.<>c__DisplayClass12_0`2.<AddTypedClientCore>b__0(IServiceProvider s)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
         at Microsoft.AspNetCore.Components.ComponentFactory.<>c__DisplayClass6_0.<CreateInitializer>g__Initialize|2(IServiceProvider serviceProvider, IComponent component)
         at Microsoft.AspNetCore.Components.ComponentFactory.PerformPropertyInjection(IServiceProvider serviceProvider, IComponent instance)
         at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType)
```

## Current behavior
Crash when using the IAuthenticationClient despite adding the Oktaconfiguration correctly with singleton.

## Expected behavior
It should use the OktaConfiguration singleton like IOktaClient do without a problem.

## Minimal reproduction of the problem with instructions
1. Add a OktaConfiguration in singleton and a Httpclient for IAuthenticationClient.
2. Inject it and try to use it in a controller or other.

## Environment

- OS: Win 10
- Browser: 
Chrome
- .Net Framework: 
.Net 5.0

**Comment by laura-rodriguez** [comment]
Hi @pilouk ,

Thanks for reporting this and apologize for the inconvenience. I will add this to our backlog for prioritization.

We recently have a similar discussion about this here: https://github.com/okta/okta-sdk-dotnet/issues/451. I suggest you take a look and see if it's helpful.

In the meantime, are you blocked?

**Comment by pilouk** [comment]
@laura-rodriguez Thanks for the quick response! we will use the classic way for testing for now. Thanks again !

**Comment by laura-rodriguez** [comment]
Sounds good! Thank you :)

**Comment by andriizhegurov-okta** [comment]
@pilouk `OktaClient` (package Okta.Sdk) and `AuthenticationClient` (package OktaAuth.Sdk) use different configuration classes though with the same name: `Okta.Sdk.Configuration.OktaClientConfiguration` and `Okta.Sdk.Abstractions.Configuration.OktaClientConfiguration`

Therefore as a wrokaround you need to configure them both like so:

```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddHttpClient<IOktaClient, OktaClient>();
    services.AddHttpClient<IAuthenticationClient, AuthenticationClient>();
    services.AddSingleton(new Okta.Sdk.Configuration.OktaClientConfiguration
    {
       OktaDomain = Configuration["Management:Okta:Domain"],
       Token = Configuration["Management:Okta:Token"]
    });
    services.AddSingleton(new Okta.Sdk.Abstractions.Configuration.OktaClientConfiguration
    {
       OktaDomain = Configuration["Management:Okta:Domain"],
       Token = Configuration["Management:Okta:Token"]
    });
}
```
This may look cumbersome, but since these packages will be superseded by Idx Sdk, we have no plans to improve them at this time.
